import fertilizer from '../assets/images/fertilizzante.jpeg';

const products = [
	{
		name: 'Kimura',
		description:
			'PREVIENE E CURA LA CARENZA DI RAME MIGLIORA LO STATO NUTRIZIONALE DELLA PIANTA PROMUOVE I MECCANISMI ENDOGENI DI DIFESA AZIONE ANTISTRESS',
		image: fertilizer,
	},
	{
		name: 'Kimura',
		description:
			'PREVIENE E CURA LA CARENZA DI RAME MIGLIORA LO STATO NUTRIZIONALE DELLA PIANTA PROMUOVE I MECCANISMI ENDOGENI DI DIFESA AZIONE ANTISTRESS',
		image: fertilizer,
	},
	{
		name: 'Kimura',
		description:
			'PREVIENE E CURA LA CARENZA DI RAME MIGLIORA LO STATO NUTRIZIONALE DELLA PIANTA PROMUOVE I MECCANISMI ENDOGENI DI DIFESA AZIONE ANTISTRESS',
		image: fertilizer,
	},
	{
		name: 'Kimura',
		description:
			'PREVIENE E CURA LA CARENZA DI RAME MIGLIORA LO STATO NUTRIZIONALE DELLA PIANTA PROMUOVE I MECCANISMI ENDOGENI DI DIFESA AZIONE ANTISTRESS',
		image: fertilizer,
	},
	{
		name: 'Kimura',
		description:
			'PREVIENE E CURA LA CARENZA DI RAME MIGLIORA LO STATO NUTRIZIONALE DELLA PIANTA PROMUOVE I MECCANISMI ENDOGENI DI DIFESA AZIONE ANTISTRESS',
		image: fertilizer,
	},
	{
		name: 'Kimura',
		description:
			'PREVIENE E CURA LA CARENZA DI RAME MIGLIORA LO STATO NUTRIZIONALE DELLA PIANTA PROMUOVE I MECCANISMI ENDOGENI DI DIFESA AZIONE ANTISTRESS',
		image: fertilizer,
	},
];

export default products;
